version: '3'
services:
  server:
    build: .
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=docker-compose
    depends_on:
      - pg

  pg:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
